AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
